# Class 02: Intro to R
In-Class Exercises

## 1.2 Operators

Choose the appropriate arithmetic operator to determine how many times does 11 go into 1,323,575 (not including the remainder)

In [ ]:
1323575 %/% 11

[1] 120325

In [ ]:
as.integer(1323576 / 11)

[1] 120325

Using the previous example, determine what the remainder is in the division problem.

In [ ]:
1323575 %% 11

[1] 0

Using the following, already defined variables, use `relational operators` to return TRUE if `x` is equivalent to `y`, and `z` is ***not*** equivalent to `a`

In [ ]:
x <- 10
y <- 10
z <- 20
a <- 20

#--- Add code below
(x==y) & (z!=a)

[1] FALSE

Use the same variables as above and use `relational operators` to determine if `x` is equivalent to `y`, or `z` is equivalent to `a`

In [ ]:
(x==y) | (z==a)

[1] TRUE

##1.3 Data types, variables, and Data Structures

What are the two methods of assigning data to a variable in R? Please show an example of each. Are there any differences?

In [ ]:
a <- 10
#-- or
a = 10

Declare a variable named `i_am_a_variable` and assign the boolean value of True

In [ ]:
i_am_a_variable <- TRUE

Create a variable called `x` and set it equal to 10. Add 5 to `x` and print the final result.

In [ ]:
x <- 10
x <- x + 5
print(x)

[1] 15

In [ ]:
x <- 10
print(x+5)

[1] 15

Create an atomic vector with the following numbers. Print the sum of the vector using the built-in sum function.
- 1,5,7,2,3,4

In [ ]:
a <- c(1, 5, 7, 2, 3, 4)

In [ ]:
sum(a)

[1] 22

Create an atomic vector with the following values. What happens and why?
- FALSE, TRUE, 2,3,"four", 5

In [ ]:
a <- c(FALSE, TRUE, 2, 3, "four", 5)

In [ ]:
#-- Since atomic vectors can only store a single data type within
#-- one data structure, it automatically converts all of the data
#-- types to characters
a

[1] "FALSE" "TRUE"  "2"     "3"     "four"  "5"

Create a list with the numbers 10-15. Print the first item in the list using indexing.

In [ ]:
a <- 10:15
print(a[1])

[1] 10

Create a named dictionary of key-value pairs where the keys are states and the values are capitals. Do this for no more than 4 states.

In [ ]:
states <- c("Virginia"="Richmond", "North Carolina"="Raleigh")

Print the capital for a state using proper key-based indexing of the dictionary

In [ ]:
states["Virginia"]

  Virginia
"Richmond"

In [ ]:
states[["Virginia"]]

[1] "Richmond"

What happens when you run the following code? Explain why it happens.

In [ ]:
#-- This creates an error because of the datatypes.
#-- R is trying to do addition, and would expect numeric
#-- data types. It instead receives character types,
#-- which creates an error
"a" + "b"

ERROR: Error in "a" + "b": non-numeric argument to binary operator

## 1.4 Control Flows

Use a for-loop to iterate over a list that you define that computes the modulus of each value in the list divided into 105. Your list should include numbers for 1-10.

In [ ]:
for (i in 1:10){
  print(105 %% i)
}

[1] 0
[1] 1
[1] 0
[1] 1
[1] 0
[1] 3
[1] 0
[1] 1
[1] 6
[1] 5

In [ ]:
divisor <- 105
for (i in 1:10){
  result <- divisor %% i
  print(result)
}

[1] 0
[1] 1
[1] 0
[1] 1
[1] 0
[1] 3
[1] 0
[1] 1
[1] 6
[1] 5

Build on the previous question and use an if-statement to only print numbers that divide evenly into 105.

In [ ]:
for (i in 1:10){
  mod_result <- 105 %% i
  if (mod_result == 0){
    print(i)
  }
}

[1] 1
[1] 3
[1] 5
[1] 7

In [ ]:
for (i in 1:10){
  mod_result <- 1053 %% i
  if (mod_result == 1){
    print(i)
  }
}

[1] 2
[1] 4

In [ ]:
for (i in 1:100){
  mod_result <- 1051 %% i
  if (mod_result == 1){
    print(i)
  }
}

[1] 2
[1] 3
[1] 5
[1] 6
[1] 7
[1] 10
[1] 14
[1] 15
[1] 21
[1] 25
[1] 30
[1] 35
[1] 42
[1] 50
[1] 70
[1] 75

In [ ]:
divisor <- 105
for (i in 1:10){
  result <- divisor %% i
  if (result == 1){
    print(i)
  }
}

[1] 2
[1] 4
[1] 8

In [ ]:
divisor <- 105
for (i in 1:10){
  result <- divisor %% i
  if (result == 1){
    print(i)
  }
}

In [ ]:
mod_func <- function(divisor, l, denominator){
  for (i in l){
    result <- divisor %% i
    if (result == denominator){
      print(i)
  }
}
}

In [ ]:
mod_func(105, 1:10, 0)

[1] 1
[1] 3
[1] 5
[1] 7

## 1.5 Functions (R and Python!)

Write a function called `max_finder` that takes 2 numbers as an input, and returns the max. Hint, you may need if-statements...

Call the function where x=4, y=8

R

Python

Write a function called `scalar` that takes a 2 arguments, 1) a list of numbers, and 2) an optional scalar to multiply each number in the list by. The second argument should default to 1. The function should return the scaled list.

Call the function with a list of 1, 2, 3 and a scaler of 2

R

Python