# Class 02: Intro to R
In-Class Exercises

## 1.2 Operators

Choose the appropriate arithmetic operator to determine how many times does 11 go into 1,323,575 (not including the remainder)

Using the previous example, determine what the remainder is in the division problem.

Using the following, already defined variables, use `relational operators` to return TRUE if `x` is equivalent to `y`, and `z` is ***not*** equivalent to `a`, otherwise FALSE

In [ ]:
x <- 10
y <- 10
z <- 20
a <- 20

#--- Add code below
x==y & z != a
#TRUE & FALSE
#FALSE

[1] FALSE

Use the same variables as above and use `relational operators` to determine if `x` is equivalent to `y`, or `z` is equivalent to `a`

##1.3 Data types, variables, and Data Structures

What are the two methods of assigning data to a variable in R? Please show an example of each. Are there any differences?

Declare a variable named `i_am_a_variable` and assign the boolean value of True

Create a variable called `x` and set it equal to 10. Add 5 to `x` and print the final result.

Create an atomic vector with the following numbers. Print the sum of the vector using the built-in sum function.
- 1,5,7,2,3,4

Create an atomic vector with the following values. What happens and why?
- FALSE, TRUE, 2,3,"four", 5

Create a list with the numbers 10-15. Print the first item in the list using indexing.

Create a named dictionary of key-value pairs where the keys are states and the values are capitals. Do this for no more than 4 states.

Print the capital for a state using proper key-based indexing of the dictionary

What happens when you run the following code? Explain why it happens.

In [ ]:

"a" + "b"

## 1.4 Control Flows

Use a for-loop to iterate over a list that you define that computes the modulus of each value in the list divided into 105. Your list should include numbers for 1-10.

Build on the previous question and use an if-statement to only print numbers that divide evenly into 105.

Write code to create a list of lists that contain numeric values from 1 to the current number, with the list ending with the number 10. The output should look like ....
```
list(
  c(1),
  c(1,2),
  c(1,2,3),
  ....
  c(1,2,3,4,5,6,7,8,9,10),
)
```

## 1.5 Functions (R and Python!)

Write a function called `max_finder` that takes 2 numbers as an input, and returns the max. Hint, you may need if-statements...

Call the function where x=4, y=8

R

Python

Write a function called `scalar` that takes a 2 arguments, 1) a list of numbers, and 2) an optional scalar to multiply each number in the list by. The second argument should default to 1. The function should return the scaled list.

Call the function with a list of 1, 2, 3 and a scaler of 2

R

Python